// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyUfPBaseO1BvVk990MMdANxPb7B_Xj6k',
    appId: '1:585906745497:android:40453676def4fa2c300808',
    messagingSenderId: '585906745497',
    projectId: 'hadyr-94932',
    storageBucket: 'hadyr-94932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQEwgxROVOKSWUBWfZhox-3VVeQW02cD0',
    appId: '1:585906745497:ios:5941027b4d64a9f7300808',
    messagingSenderId: '585906745497',
    projectId: 'hadyr-94932',
    storageBucket: 'hadyr-94932.firebasestorage.app',
    iosClientId: '585906745497-lac77o8a1c9ndbs4r2thrqqf2b53h9ng.apps.googleusercontent.com',
    iosBundleId: 'com.lildev.hadyr',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUbYpCCCOqDKUXqILfm77KcYb4uRkOf7Y',
    appId: '1:585906745497:web:ada36d319b141f9a300808',
    messagingSenderId: '585906745497',
    projectId: 'hadyr-94932',
    authDomain: 'hadyr-94932.firebaseapp.com',
    storageBucket: 'hadyr-94932.firebasestorage.app',
  );

}